
import Home from "@/Pages/Home/Home";

export const metadata = {
  title: "SeeHDmovie: Movie Download",
  description: "latest Hollywood Movie Download, Bollywood Movie Download, and South Indian Movie Download in HD quality. Fast movie download, no registration required. New movie releases updated daily! - seeHDmovieGenerated by create next app",
   keywords:"HD movie download, Bollywood Movie Download, Hollywood Movie Download, Dual audio Movie Download, 720p movies, 1080p movies, full movie download, free movie download, Hindi dubbed movies, South Indian movies, movie download site, latest movies 2025, seehdmovie, seehdmovie.xyz",
    canonical:"https://seehdmovie.xyz/"
};

export default function Page() {
  return (
    <>
     <Home />
    </>
  );
}
